version: "3.9"
services:
  redis:
    container_name: redis-treinamento
    image: redis
    ports:
      - 6379:6379

  mongodb:
    container_name: mongodb-treinamento
    image: mongodb/mongodb-community-server:5.0.4-ubuntu2004-20231208T082333Z
    ports:
      - 27017:27017
    volumes:
      - db-treinamento:/data/db

volumes:
  db-treinamento: